[package]
name = "generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "generator"
path = "src/generate_lucide.rs"
#path = "src/compress.rs"

[dependencies]
leptos = { version = "0.5.0-rc3", features = ["csr"] }
leptos_meta ={ version = "0.5.0-rc3", features = ["csr"] }
strum = "0.25"
strum_macros = "0.25"
convert_case = "0.6.0"
scraper = "0.17.1"
weezl = "0.1.7"
base64 = "0.21.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
toml = "0.8.0"





