[package]
name = "generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "generator"
path = "src/generator.rs"

[dependencies]
leptos = { version = "0.4.10", features = ["csr"] }
leptos_meta ={ version = "0.4.10", features = ["csr"] }
strum = "0.25"
strum_macros = "0.25"
convert_case = "0.6.0"
scraper = "0.17.1"



