/// Round-trip safe Cargo.toml manipulation.
/// Only mutates the [features] table, preserving all other sections.
pub struct CargoToml {
    doc: toml::Value,
}

impl CargoToml {
    pub fn load(path: String) -> Self {
        let content = std::fs::read_to_string(&path).expect("read Cargo.toml");
        let doc: toml::Value = toml::from_str(&content).expect("parse Cargo.toml");
        Self { doc }
    }

    pub fn features(&mut self) -> &mut toml::value::Table {
        self.doc
            .get_mut("features")
            .and_then(|v| v.as_table_mut())
            .expect("[features] table in Cargo.toml")
    }

    pub fn store(&self, path: String) {
        let content = toml::to_string_pretty(&self.doc).unwrap();
        let annotated = annotate_features(&content);
        std::fs::write(&path, annotated).expect("write Cargo.toml");
    }
}

/// Inserts a `# Generated by codegen ...` line above the `[features]`
/// header so a human editing the file knows the table is overwritten.
fn annotate_features(content: &str) -> String {
    const MARKER: &str = "[features]";
    const COMMENT: &str = "# Generated by codegen/src/generate_lucide.rs -- do not edit by hand.\n";
    match content.find(MARKER) {
        Some(idx) => {
            let mut out = String::with_capacity(content.len() + COMMENT.len());
            out.push_str(&content[..idx]);
            out.push_str(COMMENT);
            out.push_str(&content[idx..]);
            out
        }
        None => content.to_string(),
    }
}
