[package]
name = "lucide-icon-site"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.0-rc2", features = ["csr"] }
leptos_meta ={ version = "0.5.0-rc2", features = ["csr"] }
strum = "0.25"
strum_macros = "0.25"
lucide_icons= { path = "./lucide_icons", features = ["all_icons"] }
convert_case = "0.6.0"

[package.metadata.leptos]
name = "lucid-icons"
version = "0.1.0"
edition = "2021"




