[package]
name = "lucide-icons-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.5.7", features = ["csr"] }
leptos_meta ={ version = "0.5.7", features = ["csr"] }
leptos_router= { version = "0.5.7", features = ["csr"] }
strum = "0.25"
strum_macros = "0.25.3"
lepticons= { path = "./lepticons", features = ["default"] }
convert_case = "0.6.0"
web-sys = { version = "0.3.67", features = ["Window", "Storage"] }

[package.metadata.leptos]
name = "lucid-icons-demo"
version = "0.1.0"
edition = "2021"
lib-profile-release = "wasm-release"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1



