[package]
name = "lucid-icons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.4.10", features = ["csr"] }
leptos_meta ={ version = "0.4.10", features = ["csr"] }
# styled = "0.1.41"
# stylist = "0.12.1"

# [features]
# "leptos_meta/hydrate", "leptos_router/hydrate",
# hydrate = ["leptos/hydrate",  "leptos_image/hydrate"]

[package.metadata.leptos]
name = "lucid-icons"
version = "0.1.0"
edition = "2021"
# assets-dir = "dist"
# lib-features = ["hydrate"]




